# Generated by Django 2.0.7 on 2022-11-10 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserUploads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Job_Description', models.TextField(blank=True, null=True)),
                ('Resume', models.FileField(default='No file chosen', upload_to='uploads/')),
            ],
        ),
    ]
